version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip google-chrome-stable
      - run:
          name: Set up Python Virtual Environment
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
      - run:
          name: Install Python Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Behave tests
          command: |
            behave features/business.feature

workflows:
  version: 2
  main:
    jobs:
      - build
