version: 2.1
orbs:
  python: circleci/python@1.1.0
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Google Chrome
          command: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-stable_current_amd64.deb
            sudo apt-get -f install
      - run:
            name: Set the Python Virtual Environment
            command: |
                python -m venv venv
                source venv/bin/activate
                pip install --upgrade pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:                    
          command: |
            behave features/business.feature

workflows:
  main:
    jobs:
      - build
